name: "Build and publish to PyPI"
description: >
  This composite action builds a Python package's distribution with the
  PyPA's build tool (PEP517) and uploads it to PyPI.
inputs:
  pypi-token:
    description: "Token for PyPI"
    required: true
  python-version:
    description: "Python version"
    required: true
  upload:
    description: "Enable PyPI Uploads"
    required: false
    default: "true"
runs:
  using: "composite"
  steps:
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ inputs.python-version }}

    - name: Python install
      shell: bash
      run: |
        python -m pip install --upgrade pip
        python -m pip install --upgrade build

    - name: Install twine for check
      shell: bash
      if: fromJSON(inputs.upload) == false
      run: |
        python -m pip install --upgrade twine

    - name: Build
      shell: bash
      run: python -m build

    - name: Check packaging
      shell: bash
      if: fromJSON(inputs.upload) == false
      run: |
        twine check dist/*

    - name: Publish
      if: fromJSON(inputs.upload) == true
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        user: __token__
        password: ${{ inputs.pypi-token }}
