name: "Build and publish to PyPI"
description: >
  This composite action builds a Python package's distribution with the
  PyPA's build tool (PEP517) and uploads it to PyPI.
inputs:
  pypi-token:
    description: "Token for PyPI"
    required: true
  python-version:
    description: "Python version"
    required: true
runs:
  using: "composite"
  steps:
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ inputs.python-version }}

    - name: Python install
      run: |
        python -m pip install --upgrade pip
        python -m pip install --upgrade build

    - name: Build
      run: python -m build

    - name: Publish
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        user: __token__
        password: ${{ inputs.pypi-token }}
