name: "Build and publish to PyPI"
description: >
  This composite action builds a Python package's distribution with uv and
  uploads it to PyPI.
inputs:
  upload:
    description: "Enable PyPI Uploads"
    required: false
    default: "true"
  working-directory:
    description: "Working directory"
    required: false
    default: "."
runs:
  using: "composite"
  steps:
    - name: Set up uv
      uses: astral-sh/setup-uv@v6
      with:
        enable-cache: false

    - name: Build the package
      run: uv build --no-sources
      shell: bash
      working-directory: ${{ inputs.working-directory }}

    - name: Publish
      if: fromJSON(inputs.upload) == true
      run: uv publish
      shell: bash
      working-directory: ${{ inputs.working-directory }}
